### ISSUE TITLE
Support for Azure Blob storage

### ISSUE THREAD

**Issue by SimonFrauenschuh** [micronaut-projects/micronaut-eclipsestore#62]
### Feature description

EclipseStore supports AzureBlobStorage (see [their documentation](https://docs.eclipsestore.io/manual/storage/storage-targets/blob-stores/azure-storage.html)).

So supporting also Azure Blob storage would be nice

**Comment by SimonFrauenschuh** [comment]
I am willing to do that but I do not have permissions to push to a new branch.
Could someone please take this over or grant access to me?

**Comment by SimonFrauenschuh** [comment]
I've added a [pull request](https://github.com/micronaut-projects/micronaut-eclipsestore/pull/65) for the supporting Azure.
Help wanted ;D

**Comment by sdelamo** [comment]
@SimonFrauenschuh Thanks for your contribution
